### ISSUE TITLE
vscode Remote-SSH 连接失败

### ISSUE THREAD

**Issue by CongratulateWE** [CongratulateWE/NoteBook#66]
问题：
开发机249无法连接
但是另一台虚拟机49连接是正常的

错误日志：
```bash
[18:26:44.754] Log Level: 2
[18:26:44.757] remote-ssh@0.63.0
[18:26:44.757] darwin x64
[18:26:44.758] SSH Resolver called for "ssh-remote+fe-dev", attempt 1
[18:26:44.758] "remote.SSH.useLocalServer": true
[18:26:44.758] "remote.SSH.sshPath": undefined
[18:26:44.758] "remote.SSH.sshConfigurationFile": undefined
[18:26:44.759] "remote.SSH.useFlock": true
[18:26:44.759] "remote.SSH.lockfilesInTmp": false
[18:26:44.759] "remote.SSH.localServerDownload": auto
[18:26:44.759] "remote.SSH.remoteServerListenOnSocket": false
[18:26:44.759] "remote.SSH.showLoginTerminal": false
[18:26:44.759] SSH Resolver called for host: fe-dev
[18:26:44.759] Setting up SSH remote "fe-dev"
[18:26:44.762] Acquiring local install lock: /var/folders/w0/3x7lvymn0sq6vhp336kgs2p00000gn/T/vscode-remote-ssh-fe-dev-install.lock
[18:26:44.773] Looking for existing server data file at /Users/moonzno/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-fe-dev-ea3859d4ba2f3e577a159bc91e3074c5d85c0523-0.63.0/data.json
[18:26:44.774] Using commit id "ea3859d4ba2f3e577a159bc91e3074c5d85c0523" and quality "stable" for server
[18:26:44.777] Install and start server if needed
[18:26:44.781] Checking ssh with "ssh -V"
[18:26:44.790] > OpenSSH_8.1p1, LibreSSL 2.7.3

[18:26:44.794] askpass server listening on /var/folders/w0/3x7lvymn0sq6vhp336kgs2p00000gn/T/vscode-ssh-askpass-08e7ce121869fad3dec6df8ce7f2abfc0bd0a073.sock
[18:26:44.794] Spawning local server with {"ipcHandlePath":"/var/folders/w0/3x7lvymn0sq6vhp336kgs2p00000gn/T/vscode-ssh-askpass-041b78a1001eb5a8db0fba79ccce0fe938616c94.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","52529","-o","ConnectTimeout=15","fe-dev"],"dataFilePath":"/Users/moonzno/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-fe-dev-ea3859d4ba2f3e577a159bc91e3074c5d85c0523-0.63.0/data.json"}
[18:26:44.794] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/moonzno/.vscode/extensions/ms-vscode-remote.remote-ssh-0.63.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/moonzno/.vscode/extensions/ms-vscode-remote.remote-ssh-0.63.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/w0/3x7lvymn0sq6vhp336kgs2p00000gn/T/vscode-ssh-askpass-08e7ce121869fad3dec6df8ce7f2abfc0bd0a073.sock"}
[18:26:44.797] Spawned 5564
[18:26:44.900] > local-server> Spawned ssh: 5565
[18:26:44.904] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[18:26:45.599] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:5+7OrAGLXjREKbRC0DdS5sdmyiUnOMAqD8MDv2fFpZc
[18:26:45.924] stderr> Authenticated to 10.10.14.249 ([10.10.14.249]:22).
[18:26:46.021] > Linux host-10-10-14-249 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64
> 
> The programs included with the Debian GNU/Linux system are free software;
> the exact distribution terms for each program are described in the
> individual files in /usr/share/doc/*/copyright.
> 
> Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
> permitted by applicable law.
[18:27:01.802] Terminating local server
[18:27:01.809] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (/Users/moonzno/.vscode/extensions/ms-vscode-remote.remote-ssh-0.63.0/out/extension.js:1:64156)
	at Timeout._onTimeout (/Users/moonzno/.vscode/extensions/ms-vscode-remote.remote-ssh-0.63.0/out/extension.js:1:280517)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)
[18:27:01.811] Local server exit: 15
[18:27:01.815] ------
```

**Comment by CongratulateWE** [comment]
尝试解决：

1、更新vscode
我记得之前有这个问题，当时解决办法是更新vscode，使用vscode-inside也可以解决，可能是版本的问题。
但是没用

2、重启电脑，不行

3、有人说默认的shell需要是bash，其他的就不行，这个也没用

4、修改 remote.SSH.useLocalServer 为false，（可视化界面里是去掉打勾），成功

>本地服务器启用一种连接模式，使用单个连接在窗口之间共享和跨窗口重新加载。这使得打开新窗口更快，并减少了需要输入密码的次数。

不清楚是什么原因，看报错提示确实是 Local server 启动失败了

参考这个[issue](https://github.com/microsoft/vscode-remote-release/issues/3723#issuecomment-735965298)
